using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using NileChain.Application.Interfaces;
using NileChain.Application.Validation;
using NileChain.Infrastructure.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;

namespace NileChain.Infrastructure.Services;

public class CloudinaryService : ICloudinaryService
{
    private readonly Cloudinary _cloudinary;

    /// <summary>
    /// Residual: Cloudinary returns a SecureUrl for authenticated assets, but delivery
    /// ideally uses signed URLs. Callers should treat URLs as non-public until signed delivery is wired.
    /// </summary>
    public const string AuthenticatedDeliveryResidual =
        "Uploads use type=authenticated; signed delivery URLs are not yet generated by the API.";

    public CloudinaryService(IOptions<CloudinaryOptions> options)
    {
        var cloudinaryOptions = options.Value;
        var account = new Account(
            cloudinaryOptions.CloudName,
            cloudinaryOptions.ApiKey,
            cloudinaryOptions.ApiSecret);
        _cloudinary = new Cloudinary(account);
    }

    public async Task<(string Url, string PublicId)> UploadAsync(IFormFile file)
    {
        await using var stream = file.OpenReadStream();
        var validation = FileUploadValidation.Validate(
            file.FileName,
            file.ContentType,
            file.Length,
            stream);

        if (!validation.IsValid)
            throw new InvalidOperationException(validation.ErrorMessage ?? "Invalid upload.");

        var uploadParams = new RawUploadParams
        {
            File = new FileDescription(file.FileName, stream),
            UseFilename = false,
            UniqueFilename = true,
            // Prefer private/authenticated delivery when the Cloudinary API allows it.
            Type = "authenticated"
        };

        var result = await _cloudinary.UploadAsync(uploadParams);
        if (result.Error is not null)
            throw new InvalidOperationException(result.Error.Message);

        var url = result.SecureUrl?.ToString()
                  ?? result.Url?.ToString()
                  ?? string.Empty;

        return (url, result.PublicId);
    }

    public async Task DeleteAsync(string publicId)
    {
        var deleteParams = new DeletionParams(publicId)
        {
            ResourceType = ResourceType.Raw
        };
        // Authenticated uploads use type=authenticated; destroy with matching type when supported.
        deleteParams.Type = "authenticated";
        await _cloudinary.DestroyAsync(deleteParams);
    }
}
