<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NileChain.Domain\NileChain.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\*.ttf" />
    <EmbeddedResource Include="Resources\nilechain-mark.png" />
    <EmbeddedResource Include="Resources\nilechain-mark-light.png" />
    <Content Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
